In [1]:
import os
import random
import numpy as np
import pandas as pd

In [2]:
path = '/home/nyar/Documents/all-mias/'

In [3]:
for dirname, _, filenames in os.walk(path):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/home/nyar/Documents/all-mias/mdb056.pgm
/home/nyar/Documents/all-mias/mdb099.pgm
/home/nyar/Documents/all-mias/mdb020.pgm
/home/nyar/Documents/all-mias/mdb095.pgm
/home/nyar/Documents/all-mias/mdb206.pgm
/home/nyar/Documents/all-mias/mdb256.pgm
/home/nyar/Documents/all-mias/mdb171.pgm
/home/nyar/Documents/all-mias/mdb189.pgm
/home/nyar/Documents/all-mias/mdb025.pgm
/home/nyar/Documents/all-mias/mdb114.pgm
/home/nyar/Documents/all-mias/mdb130.pgm
/home/nyar/Documents/all-mias/mdb161.pgm
/home/nyar/Documents/all-mias/mdb295.pgm
/home/nyar/Documents/all-mias/mdb109.pgm
/home/nyar/Documents/all-mias/mdb033.pgm
/home/nyar/Documents/all-mias/mdb015.pgm
/home/nyar/Documents/all-mias/mdb121.pgm
/home/nyar/Documents/all-mias/mdb272.pgm
/home/nyar/Documents/all-mias/mdb112.pgm
/home/nyar/Documents/all-mias/mdb004.pgm
/home/nyar/Documents/all-mias/mdb313.pgm
/home/nyar/Documents/all-mias/mdb030.pgm
/home/nyar/Documents/all-mias/mdb252.pgm
/home/nyar/Documents/all-mias/mdb127.pgm
/home/nyar/Docum

In [4]:
info = pd.read_csv(path+'Info.txt', sep=' ')
info = info.drop('Unnamed: 7', axis=1)
info

REFNUM BG CLASS SEVERITY      X      Y  RADIUS
0    mdb001  G  CIRC        B  535.0  425.0   197.0
1    mdb002  G  CIRC        B  522.0  280.0    69.0
2    mdb003  D  NORM      NaN    NaN    NaN     NaN
3    mdb004  D  NORM      NaN    NaN    NaN     NaN
4    mdb005  F  CIRC        B  477.0  133.0    30.0
..      ... ..   ...      ...    ...    ...     ...
325  mdb318  D  NORM      NaN    NaN    NaN     NaN
326  mdb319  D  NORM      NaN    NaN    NaN     NaN
327  mdb320  D  NORM      NaN    NaN    NaN     NaN
328  mdb321  D  NORM      NaN    NaN    NaN     NaN
329  mdb322  D  NORM      NaN    NaN    NaN     NaN

[330 rows x 7 columns]

In [5]:
info.dropna(subset=['SEVERITY'], inplace=True)
info.reset_index(inplace=True)
info

index  REFNUM BG CLASS SEVERITY      X      Y  RADIUS
0        0  mdb001  G  CIRC        B  535.0  425.0   197.0
1        1  mdb002  G  CIRC        B  522.0  280.0    69.0
2        4  mdb005  F  CIRC        B  477.0  133.0    30.0
3        5  mdb005  F  CIRC        B  500.0  168.0    26.0
4       10  mdb010  F  CIRC        B  525.0  425.0    33.0
..     ...     ... ..   ...      ...    ...    ...     ...
118    281  mdb274  F  MISC        M  127.0  505.0   123.0
119    297  mdb290  D  CIRC        B  337.0  353.0    45.0
120    319  mdb312  F  MISC        B  240.0  263.0    20.0
121    321  mdb314  F  MISC        B  518.0  191.0    39.0
122    322  mdb315  D  CIRC        B  516.0  447.0    93.0

[123 rows x 8 columns]

In [6]:
info = info.drop([3], axis=0)
info.reset_index(inplace=True)
info

level_0  index  REFNUM BG CLASS SEVERITY      X      Y  RADIUS
0          0      0  mdb001  G  CIRC        B  535.0  425.0   197.0
1          1      1  mdb002  G  CIRC        B  522.0  280.0    69.0
2          2      4  mdb005  F  CIRC        B  477.0  133.0    30.0
3          4     10  mdb010  F  CIRC        B  525.0  425.0    33.0
4          5     12  mdb012  F  CIRC        B  471.0  458.0    40.0
..       ...    ...     ... ..   ...      ...    ...    ...     ...
117      118    281  mdb274  F  MISC        M  127.0  505.0   123.0
118      119    297  mdb290  D  CIRC        B  337.0  353.0    45.0
119      120    319  mdb312  F  MISC        B  240.0  263.0    20.0
120      121    321  mdb314  F  MISC        B  518.0  191.0    39.0
121      122    322  mdb315  D  CIRC        B  516.0  447.0    93.0

[122 rows x 9 columns]

In [7]:
ids = {}
for i in range(len(info)):
    ids[i] = info.REFNUM[i]

In [8]:
ids

{0: 'mdb001',
 1: 'mdb002',
 2: 'mdb005',
 3: 'mdb010',
 4: 'mdb012',
 5: 'mdb013',
 6: 'mdb015',
 7: 'mdb017',
 8: 'mdb019',
 9: 'mdb021',
 10: 'mdb023',
 11: 'mdb025',
 12: 'mdb028',
 13: 'mdb030',
 14: 'mdb032',
 15: 'mdb058',
 16: 'mdb059',
 17: 'mdb063',
 18: 'mdb069',
 19: 'mdb072',
 20: 'mdb075',
 21: 'mdb080',
 22: 'mdb081',
 23: 'mdb083',
 24: 'mdb090',
 25: 'mdb091',
 26: 'mdb092',
 27: 'mdb095',
 28: 'mdb097',
 29: 'mdb099',
 30: 'mdb102',
 31: 'mdb104',
 32: 'mdb105',
 33: 'mdb107',
 34: 'mdb110',
 35: 'mdb111',
 36: 'mdb115',
 37: 'mdb117',
 38: 'mdb120',
 39: 'mdb121',
 40: 'mdb124',
 41: 'mdb125',
 42: 'mdb126',
 43: 'mdb127',
 44: 'mdb130',
 45: 'mdb132',
 46: 'mdb132',
 47: 'mdb134',
 48: 'mdb141',
 49: 'mdb142',
 50: 'mdb144',
 51: 'mdb144',
 52: 'mdb145',
 53: 'mdb148',
 54: 'mdb150',
 55: 'mdb152',
 56: 'mdb155',
 57: 'mdb158',
 58: 'mdb160',
 59: 'mdb163',
 60: 'mdb165',
 61: 'mdb167',
 62: 'mdb170',
 63: 'mdb171',
 64: 'mdb175',
 65: 'mdb178',
 66: 'mdb179',
 67: 

In [9]:
label = []
for i in range(len(info)):
    if info.SEVERITY[i] == 'B':
        label.append(1)
    else:
        label.append(0)

In [10]:
label = np.array(label)

In [11]:
label

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1])

In [12]:
img_name = []
for i in range(len(label)):
    img_name.append(path+info.REFNUM[i]+'.pgm')

In [13]:
img_name = np.array(img_name)

In [14]:
img_name

array(['/home/nyar/Documents/all-mias/mdb001.pgm',
       '/home/nyar/Documents/all-mias/mdb002.pgm',
       '/home/nyar/Documents/all-mias/mdb005.pgm',
       '/home/nyar/Documents/all-mias/mdb010.pgm',
       '/home/nyar/Documents/all-mias/mdb012.pgm',
       '/home/nyar/Documents/all-mias/mdb013.pgm',
       '/home/nyar/Documents/all-mias/mdb015.pgm',
       '/home/nyar/Documents/all-mias/mdb017.pgm',
       '/home/nyar/Documents/all-mias/mdb019.pgm',
       '/home/nyar/Documents/all-mias/mdb021.pgm',
       '/home/nyar/Documents/all-mias/mdb023.pgm',
       '/home/nyar/Documents/all-mias/mdb025.pgm',
       '/home/nyar/Documents/all-mias/mdb028.pgm',
       '/home/nyar/Documents/all-mias/mdb030.pgm',
       '/home/nyar/Documents/all-mias/mdb032.pgm',
       '/home/nyar/Documents/all-mias/mdb058.pgm',
       '/home/nyar/Documents/all-mias/mdb059.pgm',
       '/home/nyar/Documents/all-mias/mdb063.pgm',
       '/home/nyar/Documents/all-mias/mdb069.pgm',
       '/home/nyar/Documents/al

In [27]:
import matplotlib.pyplot as plt
import cv2

img_path = []
last_label = []

for i in range(len(img_name)):
    img = cv2.imread(img_name[i], 0)
    img = cv2.resize(img, (90, 90))
    rows, cols = img.shape
    for angle in range(360):
        M = cv2.getRotationMatrix2D((cols/2, rows/2), angle, 1)
        img_rotated = cv2.warpAffine(img, M, (90, 90))
        img_path.append(img_rotated)
        if label[i]==1:
            last_label.append(1)
        else:
            last_label.append(0)

In [28]:
last_label = np.array(last_label)

In [29]:
last_label.size

43920

In [30]:
last_label

array([1, 1, 1, ..., 1, 1, 1])

In [31]:
last_label.ndim

1

In [32]:
last_label.shape

(43920,)

In [33]:
img_path = np.array(img_path)

In [34]:
img_path.size

355752000

In [35]:
img_path.ndim

3

In [36]:
img_path.shape

(43920, 90, 90)

In [21]:
from sklearn.svm import SVC
import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm

In [22]:
img_path

array([[[  0,   0,   0, ..., 150, 155, 163],
        [  0,   0,   0, ..., 144, 153, 160],
        [  0,   0,   0, ..., 137, 152, 155],
        ...,
        [  0,   0,   0, ..., 209, 208, 209],
        [  0,   0,   0, ..., 208, 209, 209],
        [  0,   0,   0, ..., 209, 208, 212]],

       [[  0,   0,   0, ..., 162, 173, 176],
        [  0,   0,   0, ..., 158, 170, 175],
        [  0,   0,   0, ..., 153, 167, 172],
        ...,
        [  0,   0,   0, ..., 209, 208, 209],
        [  0,   0,   0, ..., 208, 209, 210],
        [  0,   0,   0, ..., 209, 208, 211]],

       [[  0,   0,   0, ..., 176, 178, 180],
        [  0,   0,   0, ..., 174, 176, 180],
        [  0,   0,   0, ..., 172, 177, 178],
        ...,
        [  0,   0,   0, ..., 209, 208, 209],
        [  0,   0,   0, ..., 208, 209, 210],
        [  0,   0,   0, ..., 209, 209, 210]],

       ...,

       [[  0,   0,   0, ...,   1,   1,   2],
        [  0,   0,   0, ...,   2,   2,   4],
        [  0,   0,   0, ...,   3,   3,   5

In [23]:
from sklearn import metrics
from sklearn.model_selection import train_test_split
import seaborn as sns

In [24]:
x_train, x_test, y_train, y_test = train_test_split(img_path, last_label, test_size = 0.2, random_state = 42)

In [31]:
nsample, nx, ny = x_train.shape
x_train_2d = x_train.reshape((nsample, nx*ny))
x_train_2d.ndim

2

In [33]:
nsample2, mx, my = x_test.shape
x_test_2d = x_test.reshape((nsample2, mx*my))
x_test_2d.ndim

2

In [35]:
from sklearn import svm
clf = svm.SVC(kernel='rbf')
clf.fit(x_train_2d, y_train)
y_pred = clf.predict(x_test_2d)

KeyboardInterrupt: 

In [ ]:
x_train_2d.sizeape

In [ ]:
|